{
  config,
  inputs,
  pkgs,
  lib,
  ...
}:
with lib; let
  cfg = config.modules.desktop.mangowc;

  monitors = concatStringsSep "\n" (map (
      v:
        if v.disable
        then ""
        else
          replaceStrings ["\n" " "] ["" ""] ''
            monitorrule=${v.output},${toString v.mfact},${toString v.nmaster},${v.layout},
            ${toString v.transform},${toString v.scale},${toString v.x},${toString v.y},
            ${v.width},${v.height},${v.refresh_rate}
          ''
    )
    cfg.monitors);
in {
  imports = [inputs.mango.nixosModules.mango];

  options.modules.desktop.mangowc = with types; {
    enable = mkEnableOption "Whether to enable mangowc window manager";
    extraConfig = mkOpt lines "";
    monitors = mkOpt (listOf (submodule {
      options = {
        output = mkOpt str "";
        mfact = mkOpt float 0.55;
        nmaster = mkOpt int 1;
        layout = mkOpt str "tile";
        transform = mkOpt int 0;
        scale = mkOpt float 1.0;
        x = mkOpt int 0;
        y = mkOpt int 0;
        width = mkOpt str "1920";
        height = mkOpt str "1080";
        refresh_rate = mkOpt str "60";
        disable = mkOpt bool false;
      };
    })) [{}];
  };

  config = mkIf (cfg.enable) {
    programs.mango.enable = true;
    modules.desktop.type = "wayland";

    environment.sessionVariables.NIXOS_OZONE_WL = "1";

    programs.hyprlock.enable = true;
    security.pam.services.hyprlock = {};
    home.configFile."hypr/hyprlock.conf".source = "${config.flake.configDir}/hypr/hyprlock.conf";

    home.packages = [
      pkgs.mission-center
      pkgs.quickshell
      pkgs.kdePackages.qt5compat
      pkgs.kdePackages.qtsvg
      pkgs.kdePackages.qtmultimedia
      pkgs.kdePackages.qtquick3d
      pkgs.fuzzel
      pkgs.brightnessctl
      pkgs.easyeffects
      pkgs.grim
      pkgs.hyprpicker
      pkgs.swww
      pkgs.slurp
      pkgs.tesseract
      pkgs.wl-clipboard
      pkgs.wlsunset
      pkgs.xdg-desktop-portal
      pkgs.xdg-desktop-portal-wlr
      pkgs.xdg-desktop-portal-gtk
    ];

    # Add mango hm module
    home-manager.users.${config.user.name}.imports = [inputs.mango.hmModules.mango];

    home.mutableConfigFile = {
      "mango/userconfig/config.conf" = "${config.flake.configDirStr}/mango/config.conf";
      "mango/userconfig/autostart.sh" = "${config.flake.configDirStr}/mango/autostart.sh";
      "mango/userconfig/rule.conf" = "${config.flake.configDirStr}/mango/rule.conf";
      "mango/userconfig/bind.conf" = "${config.flake.configDirStr}/mango/bind.conf";
      "uwsm/env" = "${config.flake.configDirStr}/mango/env.conf";
      "quickshell" = "${config.flake.configDirStr}/quickshell";
    };

    home.extraConfig = {
      wayland.windowManager.mango = {
        enable = true;
        systemd.enable = true;

        settings = ''
          # THIS SECTION GENERATED BY NIX MODULE
          # DO NOT CHANGE THIS FILE
          #
          # USER SETTINGS IS IN ./config_mutable.conf
          # TWEAK THAT FILE INSTEAD

          # MONITORS
          ${monitors}

          # Mutable config sourcing
          source=~/.config/mango/userconfig/config.conf

          # === SECTION END ===
        '';

        autostart_sh = ''
          # see autostart.sh
          #
          # THIS SECTION GENERATED BY NIX MODULE
          # DO NOT CHANGE THIS FILE
          #
          # USER SETTINGS IS IN ./userconfig/autostart.sh
          # TWEAK THAT FILE INSTEAD

          set +e

          # Ты можешь передавать сюда пути к бинарникам из Nix Store
          # export PATH="${pkgs.bluez}/bin:${pkgs.libnotify}/bin:$PATH"

          # Или переменные, зависящие от хоста
          # export MY_WALLPAPER_DIR="${config.home.dir}/Pictures/Wallpapers"
          kitty &


          # === USER MUTABLE SCRIPT ===
          # Запускаем твой скрипт в текущем контексте.
          # Если твой скрипт сделает `echo $MY_WALLPAPER_DIR`, он увидит переменную выше!
          if [ -f ~/.config/mango/userconfig/autostart.sh ]; then
            source ~/.config/mango/userconfig/autostart.sh
          fi
          # === SECTION END ===

        '';
      };
    };
  };
}
